vim.keymap.set('n', '<C-J>', '<C-W><C-J>')
vim.keymap.set('n', '<C-H>', '<C-W><C-H>')
vim.keymap.set('n', '<C-K>', '<C-W><C-K>')
vim.keymap.set('n', '<C-L>', '<C-W><C-L>')
vim.keymap.set('n', '<leader>zi', ':e $MYVIMRC<CR>')
-- vim.keymap.set('n', '<leader><CR>', ':so $MYVIMRC<CR>')
vim.keymap.set('n', '<leader><CR>', ':so %<CR>')
vim.keymap.set('n', '<leader>w', ':up<CR>')
vim.keymap.set('n', '<leader>f', ':FZF<CR>')
vim.keymap.set('n', '<leader>b', ':Buffers<CR>')

vim.keymap.set('t', '<C-J>', '<C-\\><C-n><C-W><C-J>')
vim.keymap.set('t', '<C-H>', '<C-\\><C-n><C-W><C-H>')
vim.keymap.set('t', '<C-K>', '<C-\\><C-n><C-W><C-K>')
vim.keymap.set('t', '<C-L>', '<C-\\><C-n><C-W><C-L>')
