vim.api.nvim_set_keymap('n', '<C-J>', '<C-W><C-J>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-H>', '<C-W><C-H>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-K>', '<C-W><C-K>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-L>', '<C-W><C-L>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>zi', ':e $MYVIMRC<CR>', {noremap = true})
-- vim.api.nvim_set_keymap('n', '<leader><CR>', ':so $MYVIMRC<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader><CR>', ':so %<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>w', ':up<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>f', ':FZF<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>b', ':Buffers<CR>', {noremap = true})

vim.api.nvim_set_keymap('t', '<C-J>', '<C-\\><C-n><C-W><C-J>', {noremap = true})
vim.api.nvim_set_keymap('t', '<C-H>', '<C-\\><C-n><C-W><C-H>', {noremap = true})
vim.api.nvim_set_keymap('t', '<C-K>', '<C-\\><C-n><C-W><C-K>', {noremap = true})
vim.api.nvim_set_keymap('t', '<C-L>', '<C-\\><C-n><C-W><C-L>', {noremap = true})
