return require('packer').startup(function()

	--packer can manage itself
	use 'wbthomason/packer.nvim'

	use 'christoomey/vim-sort-motion'
	use 'christoomey/vim-system-copy'
	use 'christoomey/vim-titlecase'
	use 'easymotion/vim-easymotion'
	use 'editorconfig/editorconfig-vim'
	use 'gruvbox-community/gruvbox'
	use 'honza/vim-snippets'
	use 'inkarkat/vim-replacewithregister'
	use 'inkarkat/vim-visualrepeat'
	use 'ionide/Ionide-vim'
	use 'janko-m/vim-test'
	use 'jparise/vim-graphql'
	use 'jremmen/vim-ripgrep'
	use 'ryanoasis/vim-devicons'
	-- use 'preservim/nerdtree'
	use 'scrooloose/nerdtree'
	use 'junegunn/fzf'
	use 'junegunn/fzf.vim'
	use 'kana/vim-textobj-entire'
	use 'kana/vim-textobj-indent'
	use 'kana/vim-textobj-user'
	use 'kassio/neoterm'
	use 'kevinoid/vim-jsonc'
	use 'leafgarland/typescript-vim'
	use 'machakann/vim-highlightedyank'
	use 'mattn/emmet-vim'
	use 'mhinz/vim-grepper'
	use 'mhinz/vim-signify'
	-- use 'neoclide/coc.nvim'
	use {'neoclide/coc.nvim', branch = 'release'}
	use 'neovimhaskell/haskell-vim'
	use 'omniSharp/omniSharp-vim'
	use 'pangloss/vim-javascript'
	use 'peitalin/vim-jsx-typescript'
	use 'pprovost/vim-ps1'
	use 'rust-lang/rust.vim'
	use 'shaunsingh/moonlight.nvim'
	use 'stefandtw/quickfix-reflector.vim'
	use 'tpope/vim-commentary'
	use 'tpope/vim-fugitive'
	use 'tpope/vim-repeat'
	use 'tpope/vim-surround'
	use 'tpope/vim-unimpaired'
	use 'vim-syntastic/syntastic'
end)
